/* 
	This script ensures disjoint at funcionario table.	
*/

/*
	First,

	Modify some constraints related to 
	the instances that will be deleted 
	(it will be reverted back at the end 
	of this script).
*/

ALTER TABLE AUXILIA DROP CONSTRAINT FK2_AUXILIA;
ALTER TABLE AUXILIA ADD CONSTRAINT FK2_AUXILIA
                FOREIGN KEY(CPFPILOTO)
                REFERENCES PILOTO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE AUXILIA DROP CONSTRAINT FK3_AUXILIA;
ALTER TABLE AUXILIA ADD CONSTRAINT FK3_AUXILIA
                FOREIGN KEY(CPFCOPILOTO)
                REFERENCES COPILOTO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE OPERA DROP CONSTRAINT FK2_OPERA;
ALTER TABLE OPERA ADD CONSTRAINT FK2_OPERA
                FOREIGN KEY(CPFPILOTO)
                REFERENCES PILOTO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE OPERA DROP CONSTRAINT FK3_OPERA;
ALTER TABLE OPERA ADD CONSTRAINT FK3_OPERA
                FOREIGN KEY(IDDRONE)
                REFERENCES DRONE
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE OPPARQUE DROP CONSTRAINT FK4_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK4_OPPARQUE
                FOREIGN KEY(CPFASSISTENTE)
                REFERENCES ASSISTENTE
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE OPPARQUE DROP CONSTRAINT FK1_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK1_OPPARQUE
                FOREIGN KEY(CPFASSISTENTE)
                REFERENCES ASSISTENTE
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE OPCOMCAMERA DROP CONSTRAINT FK_OPCOMCAMERA;
ALTER TABLE OPCOMCAMERA ADD CONSTRAINT FK_OPCOMCAMERA
                FOREIGN KEY(CPFOPCAMERA)
                REFERENCES OPCAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */ 

ALTER TABLE FOTOGRAFOCRUZEIRO DROP CONSTRAINT FK1_FOTOGRAFOCRUZEIRO;
ALTER TABLE FOTOGRAFOCRUZEIRO ADD CONSTRAINT FK1_FOTOGRAFOCRUZEIRO
                FOREIGN KEY(CPFOPCAMERA, DATA)
                REFERENCES OPCOMCAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE CINEGRAFISTACRUZEIRO DROP CONSTRAINT FK1_CINEGRAFISTACRUZEIRO;
ALTER TABLE CINEGRAFISTACRUZEIRO ADD CONSTRAINT FK1_CINEGRAFISTACRUZEIRO
                FOREIGN KEY(CPFOPCAMERA, DATA)
                REFERENCES OPCOMCAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */ 

ALTER TABLE OPPARQUE DROP CONSTRAINT FK1_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK1_OPPARQUE
                FOREIGN KEY(CPFOPCAMERA, DATA)
                REFERENCES OPCOMCAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */


ALTER TABLE MANUTENCAO DROP CONSTRAINT FK1_MANUTENCAO;
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK1_MANUTENCAO
                FOREIGN KEY(CPFTECNICO)
                REFERENCES TECNICO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE UTILIZA DROP CONSTRAINT FK2_UTILIZA;
ALTER TABLE UTILIZA ADD CONSTRAINT FK2_UTILIZA
                FOREIGN KEY(SONORIZACAOID)
                REFERENCES SONORIZACAO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE PONTOSOM DROP CONSTRAINT FK1_PONTOSOM;
ALTER TABLE PONTOSOM ADD CONSTRAINT FK1_PONTOSOM
                FOREIGN KEY(IDSONORIZACAO)
                REFERENCES SONORIZACAO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE CAMERAAEREA DROP CONSTRAINT FK2_CAMERAAEREA;
ALTER TABLE CAMERAAEREA ADD CONSTRAINT FK2_CAMERAAEREA
                FOREIGN KEY(DRONE)
                REFERENCES DRONE
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE REGISTROS DROP CONSTRAINT FK_REGISTROS;
ALTER TABLE REGISTROS ADD CONSTRAINT FK_REGISTROS
                FOREIGN KEY(IDDRONE)
                REFERENCES DRONE
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE PONTOESTRUTURA DROP CONSTRAINT FK1_PONTOESTRUTURA;
ALTER TABLE PONTOESTRUTURA ADD CONSTRAINT FK1_PONTOESTRUTURA
                FOREIGN KEY(IDESTRUTURACAO)
                REFERENCES ESTRUTURACAO
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE PONTOCAMERA DROP CONSTRAINT FK1_PONTOCAMERA;
ALTER TABLE PONTOCAMERA ADD CONSTRAINT FK1_PONTOCAMERA
                FOREIGN KEY(IDCAMERA)
                REFERENCES CAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE OPPARQUE DROP CONSTRAINT FK2_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK2_OPPARQUE
                FOREIGN KEY(IDCAMERASECUNDARIA)
                REFERENCES CAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

ALTER TABLE CAMERAAEREA DROP CONSTRAINT FK1_CAMERAAEREA;
ALTER TABLE CAMERAAEREA ADD CONSTRAINT FK1_CAMERAAEREA
                FOREIGN KEY(CAMERA)
                REFERENCES CAMERA
                ON DELETE CASCADE; /* RESTRICT -> CASCADE */

/*
	Now, 

	Effectively delete instances
*/
        
/* Mantém somente os copilotos na tabela de Copilotos */
DELETE FROM COPILOTO WHERE CPF IN 
        (SELECT C.CPF FROM COPILOTO C, 
                FUNCIONARIO F WHERE C.CPF = F.CPF AND 
                F.CARGO <> 'COPILOTO');

/* Mantém somente os pilotos na tabela de pilotos */
DELETE FROM PILOTO WHERE CPF IN 
        (SELECT P.CPF FROM PILOTO P, 
                FUNCIONARIO F WHERE P.CPF = F.CPF AND 
                F.CARGO <> 'PILOTO');

/* Mantém somente os assistentes na tabela de assistentes */
DELETE FROM ASSISTENTE WHERE CPF IN 
        (SELECT A.CPF FROM ASSISTENTE A, 
                FUNCIONARIO F WHERE A.CPF = F.CPF AND 
                F.CARGO <> 'ASSISTENTE');

/* Mantém somente os op. de camera na tabela de opCamera */
DELETE FROM OPCAMERA WHERE CPF IN 
        (SELECT O.CPF FROM OPCAMERA O, 
                FUNCIONARIO F WHERE O.CPF = F.CPF AND 
                F.CARGO <> 'OPCAMERA');

/* Mantém somente os tecnicos na tabela de tecnicos */
DELETE FROM TECNICO WHERE CPF IN 
        (SELECT T.CPF FROM TECNICO T, 
                FUNCIONARIO F WHERE T.CPF = F.CPF AND 
                F.CARGO <> 'TECNICO');


/* Mantém somente SONORIZACAO na tabela de sonorizacao */
DELETE FROM SONORIZACAO WHERE ID IN 
        (SELECT S.ID FROM SONORIZACAO S, 
                EQUIPAMENTO E WHERE E.ID = S.ID AND 
                E.TIPO <> 'SONORIZACAO');

/* Mantém somente DRONE na tabela de drone */
DELETE FROM DRONE WHERE ID IN 
        (SELECT D.ID FROM DRONE D, 
                EQUIPAMENTO E WHERE E.ID = D.ID AND 
                E.TIPO <> 'DRONE');

/* Mantém somente ESTRUTURACAO na tabela de estruturacao */
DELETE FROM ESTRUTURACAO WHERE ID IN 
        (SELECT S.ID FROM ESTRUTURACAO S, 
                EQUIPAMENTO E WHERE E.ID = S.ID AND 
                E.TIPO <> 'ESTRUTURACAO');

/* Mantém somente CAMERA na tabela de camera */
DELETE FROM CAMERA WHERE ID IN 
        (SELECT C.ID FROM CAMERA C, 
                EQUIPAMENTO E WHERE E.ID = C.ID AND 
                E.TIPO <> 'CAMERA');

/* Mantém somente FOTOGRAFO na tabela de fotografocruzeiro */
DELETE FROM FOTOGRAFOCRUZEIRO FC
        USING(SELECT FC.CPFOPCAMERA, FC.DATA 
                FROM FOTOGRAFOCRUZEIRO FC, OPCOMCAMERA OC WHERE 
                        FC.CPFOPCAMERA = OC.CPFOPCAMERA AND 
                        FC.DATA = OC.DATA AND
                        OC.TIPO <> 'FOTOGRAFO') AS AUX
        WHERE FC.CPFOPCAMERA = AUX.CPFOPCAMERA AND FC.DATA = AUX.DATA;

/* Mantém somente CINEGRAFISTA na tabela de cinegrafistacruzeiro */
DELETE FROM CINEGRAFISTACRUZEIRO CC
        USING(SELECT CC.CPFOPCAMERA, CC.DATA 
                FROM CINEGRAFISTACRUZEIRO CC, OPCOMCAMERA OC WHERE 
                        CC.CPFOPCAMERA = OC.CPFOPCAMERA AND 
                        CC.DATA = OC.DATA AND
                        OC.TIPO <> 'CINEGRAFISTA') AS AUX
        WHERE CC.CPFOPCAMERA = AUX.CPFOPCAMERA AND CC.DATA = AUX.DATA;

/* 
	Finally, 
	
	Turn back modified constraints back to
	its original form 
*/
ALTER TABLE PONTOCAMERA DROP CONSTRAINT FK1_PONTOCAMERA;
ALTER TABLE PONTOCAMERA ADD CONSTRAINT FK1_PONTOCAMERA
                FOREIGN KEY(IDCAMERA)
                REFERENCES CAMERA
                ON DELETE RESTRICT; 

ALTER TABLE OPPARQUE DROP CONSTRAINT FK2_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK2_OPPARQUE
                FOREIGN KEY(IDCAMERASECUNDARIA)
                REFERENCES CAMERA
                ON DELETE RESTRICT; 

ALTER TABLE CAMERAAEREA DROP CONSTRAINT FK1_CAMERAAEREA;
ALTER TABLE CAMERAAEREA ADD CONSTRAINT FK1_CAMERAAEREA
                FOREIGN KEY(CAMERA)
                REFERENCES CAMERA
                ON DELETE RESTRICT; 

ALTER TABLE PONTOESTRUTURA DROP CONSTRAINT FK1_PONTOESTRUTURA;
ALTER TABLE PONTOESTRUTURA ADD CONSTRAINT FK1_PONTOESTRUTURA
                FOREIGN KEY(IDESTRUTURACAO)
                REFERENCES ESTRUTURACAO
                ON DELETE RESTRICT; 

ALTER TABLE CAMERAAEREA DROP CONSTRAINT FK2_CAMERAAEREA;
ALTER TABLE CAMERAAEREA ADD CONSTRAINT FK2_CAMERAAEREA
                FOREIGN KEY(DRONE)
                REFERENCES DRONE
                ON DELETE RESTRICT; 

ALTER TABLE REGISTROS DROP CONSTRAINT FK_REGISTROS;
ALTER TABLE REGISTROS ADD CONSTRAINT FK_REGISTROS
                FOREIGN KEY(IDDRONE)
                REFERENCES DRONE
                ON DELETE RESTRICT; 

ALTER TABLE PONTOSOM DROP CONSTRAINT FK1_PONTOSOM;
ALTER TABLE PONTOSOM ADD CONSTRAINT FK1_PONTOSOM
                FOREIGN KEY(IDSONORIZACAO)
                REFERENCES SONORIZACAO
                ON DELETE RESTRICT;

ALTER TABLE UTILIZA DROP CONSTRAINT FK2_UTILIZA;
ALTER TABLE UTILIZA ADD CONSTRAINT FK2_UTILIZA
                FOREIGN KEY(SONORIZACAOID)
                REFERENCES SONORIZACAO
                ON DELETE RESTRICT;

ALTER TABLE AUXILIA DROP CONSTRAINT FK2_AUXILIA;
ALTER TABLE AUXILIA ADD CONSTRAINT FK2_AUXILIA
                FOREIGN KEY(CPFPILOTO)
                REFERENCES PILOTO
                ON DELETE RESTRICT;

ALTER TABLE AUXILIA DROP CONSTRAINT FK3_AUXILIA;
ALTER TABLE AUXILIA ADD CONSTRAINT FK3_AUXILIA
                FOREIGN KEY(CPFCOPILOTO)
                REFERENCES COPILOTO
                ON DELETE RESTRICT;

ALTER TABLE OPERA DROP CONSTRAINT FK2_OPERA;
ALTER TABLE OPERA ADD CONSTRAINT FK2_OPERA
                FOREIGN KEY(CPFPILOTO)
                REFERENCES PILOTO
                ON DELETE RESTRICT;

ALTER TABLE OPERA DROP CONSTRAINT FK3_OPERA;
ALTER TABLE OPERA ADD CONSTRAINT FK3_OPERA
                FOREIGN KEY(IDDRONE)
                REFERENCES DRONE
                ON DELETE RESTRICT;

ALTER TABLE OPPARQUE DROP CONSTRAINT FK4_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK4_OPPARQUE
                FOREIGN KEY(CPFASSISTENTE)
                REFERENCES ASSISTENTE
                ON DELETE RESTRICT;

ALTER TABLE OPCOMCAMERA DROP CONSTRAINT FK_OPCOMCAMERA;
ALTER TABLE OPCOMCAMERA ADD CONSTRAINT FK_OPCOMCAMERA
                FOREIGN KEY(CPFOPCAMERA)
                REFERENCES OPCAMERA
                ON DELETE RESTRICT; 

ALTER TABLE FOTOGRAFOCRUZEIRO DROP CONSTRAINT FK1_FOTOGRAFOCRUZEIRO;
ALTER TABLE FOTOGRAFOCRUZEIRO ADD CONSTRAINT FK1_FOTOGRAFOCRUZEIRO
                FOREIGN KEY(CPFOPCAMERA, DATA)
                REFERENCES OPCOMCAMERA
                ON DELETE RESTRICT;

ALTER TABLE CINEGRAFISTACRUZEIRO DROP CONSTRAINT FK1_CINEGRAFISTACRUZEIRO;
ALTER TABLE CINEGRAFISTACRUZEIRO ADD CONSTRAINT FK1_CINEGRAFISTACRUZEIRO
                FOREIGN KEY(CPFOPCAMERA, DATA)
                REFERENCES OPCOMCAMERA
                ON DELETE RESTRICT;

ALTER TABLE OPPARQUE DROP CONSTRAINT FK1_OPPARQUE;
ALTER TABLE OPPARQUE ADD CONSTRAINT FK1_OPPARQUE
                FOREIGN KEY(CPFOPCAMERA, DATA)
                REFERENCES OPCOMCAMERA
                ON DELETE RESTRICT;

ALTER TABLE MANUTENCAO DROP CONSTRAINT FK1_MANUTENCAO;
ALTER TABLE MANUTENCAO ADD CONSTRAINT FK1_MANUTENCAO
                FOREIGN KEY(CPFTECNICO)
                REFERENCES TECNICO
                ON DELETE RESTRICT;
