SELECT OP.CPF, F.NOME, OP.INICIOCARREIRA, F.TEL1 FROM OPCAMERA OP JOIN (
	SELECT CPFOPCAMERA AS CPF
		FROM FOTOGRAFOCRUZEIRO 
		JOIN FESTANOCRUZEIRO ON IMOFESTA = IMO AND DATAFESTA = DATAINICIO
			WHERE TO_DATE('24-06-2012', 'DD-MM-YYYY') < DATAINICIO /* Data de fim menor que data início. */
				OR TO_DATE('29-11-2007', 'DD-MM-YYYY') > DATAFIM /* Data de nova festa maior que data fim. */
	UNION
	SELECT CPFOPCAMERA AS CPF
		FROM CINEGRAFISTACRUZEIRO 
		JOIN FESTANOCRUZEIRO ON IMOFESTA = IMO AND DATAFESTA = DATAINICIO
			WHERE TO_DATE('24-06-2012', 'DD-MM-YYYY') < DATAINICIO /* Data de fim menor que data início. */
				OR TO_DATE('29-11-2007', 'DD-MM-YYYY') > DATAFIM /* Data de nova festa maior que data fim. */
	UNION
	SELECT OP.CPFOPCAMERA AS CPF 
		FROM OPPARQUE OP 
		JOIN FESTANOPARQUE FP ON OP.CNPJPARQUE = FP.CNPJPARQUE AND OP.DATAINICIOPARQUE = FP.DATAINICIO 
			WHERE TO_DATE('24-06-2012', 'DD-MM-YYYY') < FP.DATAINICIO /* Data de fim menor que data início. */
				OR TO_DATE('29-11-2007', 'DD-MM-YYYY') > FP.DATAFIM /* Data de nova festa maior que data fim. */
) AS DT ON OP.CPF IN (DT.CPF) JOIN FUNCIONARIO F ON OP.CPF = F.CPF WHERE F.CARGO = 'OPCAMERA';

SELECT NOME, DATACRIACAO, ESTILOMUSICAL, TIPO 
	FROM BANDA 
	WHERE (NOME, DATACRIACAO) 
		NOT IN 
	(SELECT NOMEBANDA, DATACRIACAOBANDA FROM SHOW WHERE DATA = TO_DATE('04-04-2015', 'DD-MM-YYYY'));